### ISSUE TITLE
Maybe emphasize on "in the long run"?

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#1]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L29

Here it could lead to a misunderstanding about the chance of correct or wrong of one time decision.

**Comment by ShKlinkenberg** [comment]
How would you see this to be misunderstood? I think it is enough at this point. We dive deeper in a later stage don't you think?
