### ISSUE TITLE
"For example the null hypothesis that average media literacy in the population of children equals 5.5 on a scale from one to ten." was used as alternative hypothesis before

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#11]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L275

This example was used as alternative previously. 
"
For example the null hypothesis that average media literacy in the population of children equals 5.5 on a scale from one to ten.
"

**Comment by ShKlinkenberg** [comment]
Where exactly, and why is it a problem. Does it distract from our argumentation?

**Comment by xgaouva** [comment]
No, I do not see it is a problem now.
