### ISSUE TITLE
Not true: Now that we have determined our critical value based on our desired alpha, significance level

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#12]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L291

Critical values 2 and 9 in Figure 4.7 are not solely decided by alpha, but determined by both alpha level and n = 10 in this case.

**Comment by ShKlinkenberg** [comment]
I added : "(for our particular sample size)"
