### ISSUE TITLE
What if it is one-sided test

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#13]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L356

The sentence "
If the test statistic is outside the critical value, we reject the null hypothesis. If the test statistic is inside the critical value, we do not reject the null hypothesis.
"

What if it is one-sided test, how would I decide whether it is inside or outside of critical value?

**Comment by ShKlinkenberg** [comment]
For now we get the point across. I will review the one and two sided testing paragraph to see if we can emphasise it there
