### ISSUE TITLE
Unfortunately, the t test commands in SPSS have no option to calculate Cohen’s d.

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#15]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L548

Unfortunately, the t test commands in SPSS have no option to calculate Cohen’s d.

I assume nowadays all students have SPSS version above 26, which can calculate cohen's d.

**Comment by ShKlinkenberg** [comment]
Took that part out.
