### ISSUE TITLE
Typo:

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#16]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L608C511-L608C532

Following the same decision criteria as defined in the previous sections, the post hoc power is almost zero. This is the probability of 0 or 1 yellow candies under the alternative distribution.

Should it be: "This is the probability of 0 or **10** yellow candies under the alternative distribution."

**Comment by ShKlinkenberg** [comment]
Indeed, I changed it.
