### ISSUE TITLE
One sided p value in two sided example.

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#17]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L368

Before the sentence: 
"
This is what is meant with “at least as extreme”. this is not really intuitive, but it refers to the less likely test statistics, in our case 0, 1, 2 and 3, are even less probable than 4.
"
Only two-sided alpha level was discussed, "at least as extreme" is equal or less probable than 4, but also equal or more probable than 7?

**Comment by ShKlinkenberg** [comment]
That is indeed the case for two sided testing. Though we did not cover that yet. I think the message is clear for now.
