### ISSUE TITLE
16 or 20 candies? 

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#20]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/88045c6e2a4b23cd9cc07448e3b47106ef82a648/04-hypothesis.Rmd#L659C493-L659C573

"
Though the parameter is still the same, the expected value when we have bags of 16 cancies is now...."

**Comment by ShKlinkenberg** [comment]
HI Xin, If you find a typo, feel free to change is 😊

From: Xin Gao ***@***.***>
Date: Friday, 14 June 2024 at 12:48
To: statistical-reasoning-course-dev/Statistical-Inference-Rewrite ***@***.***>
Cc: Sharon Klinkenberg ***@***.***>, Assign ***@***.***>
Subject: [statistical-reasoning-course-dev/Statistical-Inference-Rewrite] 16 or 20 candies? (Issue #20)

https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/88045c6e2a4b23cd9cc07448e3b47106ef82a648/04-hypothesis.Rmd#L659C493-L659C573

"
Though the parameter is still the same, the expected value when we have bags of 16 cancies is now...."

**Comment by xgaouva** [comment]
Sure

From: Sharon Klinkenberg ***@***.***>
Date: Friday, 14 June 2024 at 12:51
To: statistical-reasoning-course-dev/Statistical-Inference-Rewrite ***@***.***>
Cc: Xin Gao ***@***.***>, Author ***@***.***>
Subject: Re: [statistical-reasoning-course-dev/Statistical-Inference-Rewrite] 16 or 20 candies? (Issue #20)
HI Xin, If you find a typo, feel free to change is 😊

From: Xin Gao ***@***.***>
Date: Friday, 14 June 2024 at 12:48
To: statistical-reasoning-course-dev/Statistical-Inference-Rewrite ***@***.***>
Cc: Sharon Klinkenberg ***@***.***>, Assign ***@***.***>
Subject: [statistical-reasoning-course-dev/Statistical-Inference-Rewrite] 16 or 20 candies? (Issue #20)

https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/88045c6e2a4b23cd9cc07448e3b47106ef82a648/04-hypothesis.Rmd#L659C493-L659C573

"
Though the parameter is still the same, the expected value when we have bags of 16 cancies is now...."
