### ISSUE TITLE
This is confusing: H0 states as 0.5 is the proportion before; would be better to stick with 0.5? 

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#3]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L102C354-L102C362

**Comment by ShKlinkenberg** [comment]
agree, I took out .2
