### ISSUE TITLE
Sentence is incomplete

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#5]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L147C213-L147C236

Would it be more clear: 
Assuming .2 as the machine's parameter does not ensure that every bag will contain exactly 2 yellow candies.

**Comment by ShKlinkenberg** [comment]
Sound good, I changed it.
