### ISSUE TITLE
Effect size explanation in context of yellow candies

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#8]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L177

This paragraph: 

"In the candy factory example, the true effect size is .5 - .2 = .3. This is the difference in the proportion of yellow candies in the bags. In figure [4.5](https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/issues/4.1-null-hypothesis-significance-testing.html#fig:twobinomeffect) you can see the difference in the two distributions. The true effect size is the difference in the expected value of the two distributions. In absolute terms, it it the 5 - 3, though, in terms of the parameter it is the proportion .5 - .2." 

I am not sure in the example of binomial distribution, which one makes more sense to call as "effect size", difference between parameters or expected values? It feels strange to talk effect size in this case, what does ".3" or "3" mean?

**Comment by ShKlinkenberg** [comment]
I clarified this more
