### ISSUE TITLE
"you accept a 5% chance of making a Type I error."

### ISSUE THREAD

**Issue by xgaouva** [statistical-reasoning-course-dev/Statistical-Inference-Rewrite#9]
https://github.com/statistical-reasoning-course-dev/Statistical-Inference-Rewrite/blob/8ec378f729009ca887f7bc37184b286f0ffb0f3f/04-hypothesis.Rmd#L214C224-L214C310

Suggest to add: 

you accept a 5% chance of making a Type I error, **at most, in a long run**

**Comment by ShKlinkenberg** [comment]
I don't think we would have to reiterate the long run argument again here. Didn't we cover that enough in the previous chapters?
